name: Build scraper

on:
  push:
    branches:
      - main
    paths:
      - "python-scraper/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          cd ./python-scraper
          docker build -t tmp:latest .

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          OWNER_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER_REPO/oil-tracker-scraper:latest
          docker tag tmp:latest $IMAGE_NAME
          docker push $IMAGE_NAME
