name: Build database

on:
  push:
    branches:
      - main
    paths:
      - "database/**"
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          cd ./database
          docker build -t sqlitedb:latest .

      - name: Save Docker image as tar
        run: |
          docker save sqlitedb:latest -o image.tar

      - name: Upload Docker iamge as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar
          retention-days: 1
